[project]
name = "jehon"
version = "0.0.1"
description = "My scripts"
readme = "README.md"
requires-python = ">=3.9"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
